#!/bin/bash

if [ "$1" = "" ] ; then
	cd ../alslug.dk-content &&
	find . -name '*.html' -not name 'template.html' -type f -ls 
# -exec ../$0 \{\} \;
elif [ -f "$1" ] ; then
	TARGET=$TARGET
	mkdir $( dirname $TARGET ) -pv
	(
		cat ../alslug.dk-content/template.html | sed ':a;N;$!ba;s/<section>.*/<section>/'
		cat $1					|
		sed "s/####\(.*\)####/<h4>\1<\/h4>/g"	|
		sed "s/###\(.*\)###/<h3>\1<\/h3>/g"	|
		sed "s/##\(.*\)##/<h2>\1<\/h2>/g"	|
		sed "s/#\(.*\)#/<h1>\1<\/h1>/g"
		cat ../alslug.dk-content/template.html | sed ':a;N;$!ba;s/.*<\/section>/<\/section>/'
	) > $TARGET
fi
